language: python
python:
 - "3.5"
 - "3.6"

install:
 - pip install coveralls
 - pip install coverage
 - pip install pytest-cov
 - pip install .
 
script:
 - pytest --cov=arrayqueues tests/
 
after_success:
 - coveralls
